package com.HuJuHomePage.mappers;

import com.HuJuHomePage.models.Student;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StudentMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student
//     *
//     * @mbggenerated Wed Aug 07 22:37:32 CST 2019
//     */
//    int countByExample(StudentExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student
//     *
//     * @mbggenerated Wed Aug 07 22:37:32 CST 2019
//     */
//    int deleteByExample(StudentExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student
//     *
//     * @mbggenerated Wed Aug 07 22:37:32 CST 2019
//     */
//    int deleteByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student
//     *
//     * @mbggenerated Wed Aug 07 22:37:32 CST 2019
//     */
//    int insert(Student record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student
//     *
//     * @mbggenerated Wed Aug 07 22:37:32 CST 2019
//     */
//    int insertSelective(Student record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student
//     *
//     * @mbggenerated Wed Aug 07 22:37:32 CST 2019
//     */
//    List<Student> selectByExample(StudentExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student
//     *
//     * @mbggenerated Wed Aug 07 22:37:32 CST 2019
//     */
//    Student selectByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student
//     *
//     * @mbggenerated Wed Aug 07 22:37:32 CST 2019
//     */
//    int updateByExampleSelective(@Param("record") Student record, @Param("example") StudentExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student
//     *
//     * @mbggenerated Wed Aug 07 22:37:32 CST 2019
//     */
//    int updateByExample(@Param("record") Student record, @Param("example") StudentExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student
//     *
//     * @mbggenerated Wed Aug 07 22:37:32 CST 2019
//     */
//    int updateByPrimaryKeySelective(Student record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student
//     *
//     * @mbggenerated Wed Aug 07 22:37:32 CST 2019
//     */
//    int updateByPrimaryKey(Student record);
}